import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';

const gilroy = localFont({
  src: '../../fonts/Gilroy-Regular.woff',
  variable: '--font-gilroy',
  weight: '400',
  style: 'normal',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${gilroy.variable} antialiased`}>{children}</body>
    </html>
  );
}
